server:
  port: 777
spring:
  application:
    name: chat-boot
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:db/test.db
    hikari:
      auto-commit: true
logging:
  pattern:
    console: '%d{yyyy-MM-dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n'
    file: '%d{yyyy-MM-dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n'
  file:
    name: './chat-log.log'
  level:
    root: info
    org.springframework.jdbc.core: DEBUG